/**
 * OOPSBannerApp
 *
 * This application prints "OOPS" in a banner format
 * using '*' and spaces.
 *
 * @author Daksh Kumar
 * @version 2.0
 */
public class OOPSBannerApp {

    public static void main(String[] args) {

        System.out.println("  *****  " + "  *****  " + "  ****** " + "  ****** ");
        System.out.println(" *     * " + " *     * " + " *     * " + " *     * ");
        System.out.println(" *     * " + " *     * " + " *     * " + " *       ");
        System.out.println(" *     * " + " *     * " + "  ****** " + "  *****  ");
        System.out.println(" *     * " + " *     * " + " *       " + "       * ");
        System.out.println(" *     * " + " *     * " + " *       " + " *     * ");
        System.out.println("  *****  " + "  *****  " + " *       " + "  *****  ");
    }
}
